apiVersion: v1
kind: Service
metadata:
  name: whisper
spec:
  selector:
    pod: whisper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whisper-up
  namespace: default
data:
  prod_up: |-
    apt-get install -y libsndfile1 libsndfile-dev ffmpeg
    pip install -U soundfile
    uvicorn jac_speech.stt:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: whisper
  template:
    metadata:
      labels:
        pod: whisper
      name: whisper
    spec:
      containers:
        - name: whisper
          imagePullPolicy: IfNotPresent
          image: jaseci/jac-speech:1.4.0.13
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: whisper-up